spring.application.name=soporte-backend
server.port=8083

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=785588af-9f25-4dc1-a2d9-afbe56ee1787
spring.cloud.azure.active-directory.credential.client-id=0e7d4bab-2455-4de8-bb75-c49e17617089
spring.cloud.azure.active-directory.app-id-uri=api://0e7d4bab-2455-4de8-bb75-c49e17617089

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pedidosdb}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prefetch: Procesa 1 mensaje a la vez
spring.rabbitmq.listener.simple.prefetch=1

# Reintentos con Exponential Backoff
spring.rabbitmq.listener.simple.retry.enabled=true
# 1 segundo
spring.rabbitmq.listener.simple.retry.initial-interval=1000
# 10 segundos máximo
spring.rabbitmq.listener.simple.retry.max-interval=10000
# Duplica cada intento
spring.rabbitmq.listener.simple.retry.multiplier=2.0
#3 intentos totales
spring.rabbitmq.listener.simple.retry.max-attempts=3